### ISSUE TITLE
Update store from onRouteUpdate?

### ISSUE THREAD

**Issue by jonny-harte** [le0nik/gatsby-plugin-react-redux#17]
Hi, how do I update the store from within Gatsby Browser API when using this plugin?

I need to update a `TOGGLE_MENU` action from within `onRouteUpdate`

**Comment by le0nik** [comment]
Hi, you can't access store from Gatsby Browser API.

Gatsby only provides `location` and `prevLocation` to `onRouteUpdate` and has no concept of context object or anything like that which plugins could add properties like `store` or `dispatch` to.

It can only be done from application side like so https://stackoverflow.com/a/61664193
