### ISSUE TITLE
Gatsby build is failing ERROR #95313

### ISSUE THREAD

**Issue by mskanani** [le0nik/gatsby-plugin-react-redux#19]
Hi, I have just added this plug-in to my bilingual website. Everything is working as expected in all languages (EN, AR) when using Gatsby develop.
However; when I try Gatsby build It's always failing while trying to build static HTML for the secondary language pages which is AR in my case

ERROR #95313
Building static HTML failed for path **ar**/about

Appreciate the help. Thanks!

**Comment by le0nik** [comment]
Hi.
Please provide full stacktrace and also your `package.json`, `gatsby-config.js`, `gatsby-browser.js`, `gatsby-ssr.js`.
Also am I right to assume that `gatsby build` works correctly without this plugin?

**Comment by mskanani** [comment]
Hi.. yes the build is working without the plugin. I am not using gatsby-ssr.js

success open and validate gatsby-configs - 0.208s
success load plugins - 2.083s
success onPreInit - 0.059s
success delete html and css files from previous builds - 0.005s
success initialize cache - 0.015s
success copy gatsby files - 2.559s
success onPreBootstrap - 0.009s
success source and transform nodes - 5.101s
success building schema - 0.327s
success createPages - 4.421s
success createPagesStatefully - 0.633s
success onPreExtractQueries - 0.001s
success update schema - 0.249s
success extract queries from components - 1.429s
success write out requires - 0.011s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.095s
success onPostBootstrap - 0.100s
info bootstrap finished - 33.281 s
success run static queries - 0.015s - 1/1 83.56 queries/second
success Building production JavaScript and CSS bundles - 66.209s
success Rewriting compilation hashes - 0.005s
success run page queries - 19.117s - 76/76 3.98 queries/second

ERROR #95313

Building static HTML failed for path "/ar/about/"

See our docs page for more info on this error: https://gatsby.dev/debug-html
Error:
not finished Building static HTML for pages - 10.746s

====================

gatsby-config.js:
-------------------
const {getSerializer} = require('./src/utils/getSerializer');
const {getRobotsPolicy} = require('./src/utils/getRobotsPolicy');
const {title, titleTemplate, description, siteUrl, logoImage, twitterUsername, sitemapName,phoneNumber,phoneLabel,socialLinks} = require('./config/siteConfig');

const currentEnv = process.env.GATSBY_CURRENT_ENV || process.env.NODE_ENV || 'development';

require('dotenv')
    .config({
        path: `.env.${currentEnv}`,
    });

console.log('The backend CMS url is:', process.env.BAKEND_URL);

const currentSiteUrl = currentEnv === 'development' ? siteUrl.staging : siteUrl.production;

module.exports = {
    siteMetadata: {
        title,
        titleTemplate,
        description,
        url: currentSiteUrl,
        image: logoImage,
        twitterUsername,
        siteUrl: currentSiteUrl,
        phoneNumber: phoneNumber,
        phoneLabel: phoneLabel,
        socialLinks: socialLinks,
        englishSitemapName: sitemapName.english,
        arabicSitemapName: sitemapName.arabic,
        russianSitemapName: sitemapName.russian,
    },
    plugins: [
        'gatsby-plugin-react-helmet',
        'gatsby-plugin-preload-fonts',
        {
            resolve: 'gatsby-plugin-force-trailing-slashes',
            options: {
                excludedPaths: ['/404.html', '/offers'],
            },
        },
        'svgo',
        'gatsby-plugin-sass',
        'gatsby-plugin-postcss',
        {
            resolve: 'gatsby-source-filesystem',
            options: {
                name: 'data',
                path: `${__dirname}/src/data/`,
            },
        },
        'gatsby-transformer-json',
        {
            resolve: 'gatsby-source-graphql',
            options: {
                // This type will contain remote schema Query type typeName: 'GraphCMS',
                typeName: 'GraphCMS',
                // This is the field under which it's accessible  fieldName: 'cms',
                fieldName: 'cms',
                // URL to query from  url: ',${process.env.SILVERPOP_URL}
                url: `${process.env.BAKEND_URL}/graphql`,
                refetchInterval: 720,
            },
        },
        {
            resolve: 'gatsby-plugin-google-tagmanager',
            options: {
                id: `${process.env.GTM_ID}`, 
                defaultDataLayer: function () {
                    return {};
                },

                // Include GTM in development.
                // Defaults to false meaning GTM will only be loaded in production.
                includeInDevelopment: true,
            },
        },
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `gatsby-starter-default`,
                short_name: `starter`,
                start_url: `/`,
                background_color: `#ccb77e`,
                theme_color: `#ccb77e`,
                display: `minimal-ui`,
                icon: `src/images/icon.png`, // This path is relative to the root of the site.
            },
        },
        {
            resolve: `gatsby-plugin-intl`,
            options: {
                path: `${__dirname}/src/intl`,
                languages: [`en`, `ar`, `ru`],
                // languages: [`en`, `ar`],
                defaultLanguage: `en`,
                redirect: true,
                // redirectComponent: require.resolve(`./src/components/redirect.js`),
            },
        },
        {
            resolve: 'gatsby-plugin-polyfill-io',
            options: {
                features: ['Array.prototype.map', 'fetch', 'Promise', 'URL'],
            },
        },
        'gatsby-plugin-client-side-redirect', 
        {
            resolve: 'gatsby-plugin-sitemap',
            options: {
                output: '/sitemap-arabic.xml',
                createLinkInHead: true,
                // Only include arabic pages
                exclude: ['/en/*', '/ru/*', `/ar/404`, `/ar/search`],
                serialize: getSerializer('ar'),
            },
        },
        {
            resolve: 'gatsby-plugin-sitemap',
            options: {
                output: '/sitemap-english.xml',
                createLinkInHead: true,
                // Only include english pages
                exclude: ['/ar/*', '/ru/*', '/en/404', '/en/search'],
                serialize: getSerializer('en'),
            },
        },
        {
            resolve: `gatsby-plugin-sitemap`,
            options: {
              output: `/sitemap-russian.xml`,
              createLinkInHead: true,
              // Only include Russian pages
              exclude: ["/en/*", "/ar/*", `/ru/404`, `/ru/search`],
              serialize: getSerializer('ru'),
            }
          },
        {
            resolve: 'gatsby-plugin-robots-txt',
            options: {
                policy: [getRobotsPolicy(currentEnv)],
            },
        },
        {
            resolve: `gatsby-plugin-canonical-urls`,
            options: {
                siteUrl: currentSiteUrl,
                stripQueryString: true,
            },
        },
        {
            resolve: `gatsby-plugin-react-redux`,
            options: {
              // [required] - path to your createStore module
              pathToCreateStoreModule: './src/state/createStore',
              // [optional] - options passed to `serialize-javascript`
              // info: https://github.com/yahoo/serialize-javascript#options
              // will be merged with these defaults:
              serialize: {
                space: 0,
                // if `isJSON` is set to `false`, `eval` is used to deserialize redux state,
                // otherwise `JSON.parse` is used
                isJSON: true,
                unsafe: false,
                ignoreFunction: true,
              },
              // [optional] - if true will clean up after itself on the client, default:
              cleanupOnClient: true,
              // [optional] - name of key on `window` where serialized state will be stored, default:
              windowKey: '__PRELOADED_STATE__',
            },
        },
    ],
};
=============================
gatsby-browser.js:
--------------------
exports.onInitialClientRender = () => {
    function callback(data) {
        window.userCountryCode = data.country_code;
    }

    window.callback = callback;

    var rndm_script = document.createElement('script');
    rndm_script.type = 'text/javascript';
    rndm_script.src = 'https://geoip-db.com/jsonp';
    var rndm_h = document.getElementsByTagName('script')[0];
    rndm_h.parentNode.insertBefore(rndm_script, rndm_h);
}

exports.onPreRouteUpdate = ({location, prevLocation}) => {
    for (let i = 0; i < window.dataLayer.length; i++) {
        if (window.dataLayer[i] && window.dataLayer[i].event !== 'gtm.load') {
            window.dataLayer[i] = undefined;
        }
    }
}
exports.registerServiceWorker = () => true

=========================

package.json
--------------
{
  "name": "gatsby-react-boilerplate",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "preload-fonts": "gatsby-preload-fonts",
    "develop": "env-cmd .env.development gatsby develop -H 0.0.0.0",
    "staging": "GATSBY_CURRENT_ENV=development gatsby build",
    "build": "env-cmd -f .env.production gatsby build",
    "serve": "gatsby serve",
    "start": "node server.js",
    "gh-pages": "gatsby build --prefix-paths && gh-pages -d public",
    "lint": "eslint src --fix",
    "dev": "gatsby clean && gatsby develop -H 0.0.0.0",
    "server": "cross-env NODE_ENV=development DEBUG=api node server.js"
  },
  "author": "Prototype Interactive",
  "license": "MIT",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-brands-svg-icons": "^5.9.0",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "@material-ui/core": "^4.2.1",
    "@progress/kendo-react-dropdowns": "^3.2.2",
    "axios": "^0.19.0",
    "basic-auth": "^2.0.1",
    "compression": "^1.7.4",
    "crypto-js": "^3.1.9-1",
    "debug": "^4.1.1",
    "embla-carousel": "^2.3.2",
    "express": "^4.17.1",
    "foundation-sites": "^6.5.3",
    "gatsby-plugin-canonical-urls": "^2.1.18",
    "gatsby-plugin-client-side-redirect": "0.0.2",
    "gatsby-plugin-google-tagmanager": "^2.1.7",
    "gatsby-plugin-intl": "^0.2.7-beta.0",
    "gatsby-plugin-manifest": "^2.2.9",
    "gatsby-plugin-netlify": "^2.1.25",
    "gatsby-plugin-polyfill-io": "^1.1.0",
    "gatsby-plugin-preload-fonts": "^1.0.27",
    "gatsby-plugin-react-redux": "^1.1.0",
    "gatsby-plugin-remove-trailing-slashes": "^2.1.14",
    "gatsby-plugin-robots-txt": "^1.5.0",
    "gatsby-plugin-sitemap": "^2.2.24",
    "gatsby-source-graphql": "2.1.15",
    "helmet": "^3.21.1",
    "intl": "^1.2.5",
    "intl-locales-supported": "^1.4.0",
    "jquery": "^3.4.1",
    "js-search": "^1.4.3",
    "jssor-slider": "^27.5.0",
    "materialize-css": "^1.0.0-rc.2",
    "mdbootstrap": "^4.8.7",
    "moment": "^2.24.0",
    "path": "^0.12.7",
    "progressbar.js": "^1.0.1",
    "qs": "^6.9.1",
    "react-country-region-selector": "^1.4.4",
    "react-device-detect": "^1.7.5",
    "react-elastic-carousel": "^0.3.0",
    "react-helmet": "^5.2.1",
    "react-horizontal-timeline": "^1.5.3",
    "react-html-parser": "^2.0.2",
    "react-intl": "^2.9.0",
    "react-lazyload": "^2.6.5",
    "react-number-format": "^4.2.0",
    "react-phone-number-input": "^2.3.21",
    "react-player": "^1.11.1",
    "react-redux": "^7.1.0",
    "react-responsive-modal": "^4.0.1",
    "react-scroll-to-component": "^1.0.2",
    "react-slick": "^0.25.2",
    "react-slick-rtl": "^0.23.2",
    "react-smartbanner": "^5.1.4",
    "react-tabs": "^3.0.0",
    "react-waypoint": "^9.0.2",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "serve-static": "^1.14.1",
    "simple-load-script": "^1.0.2",
    "slick-carousel": "^1.8.1",
    "styled-components": "^4.3.2"
  },
  "devDependencies": {
    "@prototype-interactive/eslint-config": "^0.1.1",
    "autoprefixer": "^9.6.1",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.6",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.3.1",
    "cross-env": "^5.2.0",
    "env-cmd": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.18.3",
    "eslint-plugin-react-hooks": "^2.4.0",
    "express-xml-bodyparser": "^0.3.0",
    "gatsby": "2.13.33",
    "gatsby-plugin-force-trailing-slashes": "^1.0.4",
    "gatsby-plugin-google-analytics": "^2.1.4",
    "gatsby-plugin-postcss": "^2.1.2",
    "gatsby-plugin-postcss-sass": "^1.0.22",
    "gatsby-plugin-react-helmet": "^3.1.2",
    "gatsby-plugin-sass": "^2.1.3",
    "gatsby-source-filesystem": "^2.1.6",
    "gatsby-transformer-json": "^2.2.2",
    "gh-pages": "^2.0.1",
    "husky": "^1.3.1",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "pretty-quick": "^1.11.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "shx": "^0.3.2",
    "svg-sprite-loader": "^4.1.6"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/PrototypeInteractive/gatsby-react-boilerplate.git"
  },
  "bugs": {
    "url": "https://github.com/PrototypeInteractive/gatsby-react-boilerplate/issues"
  },
  "homepage": "https://github.com/PrototypeInteractive/gatsby-react-boilerplate#readme"
}

**Comment by le0nik** [comment]
Can you also provide your `./src/state/createStore`?

And did you try to follow the advices on https://gatsby.dev/debug-html page, like checking if you reference window or document in your code that can be executed during SSR?

**Comment by mskanani** [comment]
import { createStore, applyMiddleware } from 'redux';
import reducers from './reducers';
import thunk from 'redux-thunk';

export default preloadedState => {
  return createStore(reducers , preloadedState, applyMiddleware(thunk));
};

Do you think it's an issue with using react-intl together with your plugin together? why it's not throwing the error for an English page?

**Comment by Mahmoud-Alsrouji-Kanani** [comment]
I am closing the issue. It turned out it's to do with referencing the window during SSR as you said. Thanks anyway!

**Comment by mskanani** [comment]
I am closing the issue. It turned out it's to do with referencing the window during SSR as you said. Thanks anyway!
