### ISSUE TITLE
How to import data from GraphQL store into Redux

### ISSUE THREAD

**Issue by saschaklatt** [le0nik/gatsby-plugin-react-redux#5]
Hi, I was wondering if there is a way to directly import data, that is stored in the GraphQL store during build time (ssr), into the redux store that is used at runtime in the browser.

At the moment I'm using a static query to fetch the data and then put it into redux after my component did mount. It would be much nicer if I could put some initial state from GraphQL into redux when I create the store.

**Comment by le0nik** [comment]
Unfortunately passing initial state from query into the redux store isn't possible outside components.

From this comment by gatsby maintainer: https://github.com/gatsbyjs/gatsby/issues/12624#issuecomment-475541835
> It's currently only possible to fetch data using
> 
> - a page query
> - a static query in a React component
>
> Since the preloadedState needs to be passed into the redux store when creating it (and since it is typically created outside the scope of a React component) it currently isn't possible to query data and pass it in as preloadedState

------------------------------------------

Another thing:
> and then put it into redux after my component did mount

The problem with this approach is that `componentDidMount`/`useEffect`/`useLayoutEffect` don't get called during SSR, so your server state doesn't get transferred to the client.

Instead you should dispatch initial data synchronously during render on the server and dispatch nothing on the client.

Here's a basic example:

```js
export const MyComponent = () => {
  const queryResult = useStaticQuery(query);

  // will be `false` during SSR and `true` in the browser
  const isStateInitialized = useSelector(state => state.isInitialized);
  if (!isStateInitialized) {
    // also set state.isInitialized to true in your reducer
    dispatch({ type: 'INITIALIZE_STATE_FROM_QUERY', payload: queryResult })
  }
};
```

It can also be done for separate parts of state if you use static queries in multiple places throughout the project. Just remember that you need to dispatch synchronously, not in `componentDidMount`/`useEffect`/`useLayoutEffect`.
