### ISSUE TITLE
How Can I Save Things To The Preloaded State (LocalStorage)?

### ISSUE THREAD

**Issue by JimLynchCodes** [le0nik/gatsby-plugin-react-redux#7]
Hi, I'm having trouble using and understanding the gatsby "preloadedState". Here is my createStore function:

```
export default preloadedState => {
  return createStore(
    combinedReducers,
    preloadedState,
    composeWithDevTools(
      applyMiddleware(
        todosCustomMiddleware(),
        loginCustomMiddleware()
      )
    ),
  );
};
```
I would like to do this and save the "loginReducer" (being composed in composeReducers) to localstorage so that even after I refresh the web page the data is still persisted in redux:
```
// preloadedState will be passed in by the gatsby plugin
export default preloadedState => {
  return createStore(
    combinedReducers,
    load({ states: ['loginCustomMiddleware'], disableWarnings: true }),
    composeWithDevTools(
      applyMiddleware(
        save({ states: ['loginCustomMiddleware'] }),
        todosCustomMiddleware(),
        loginCustomMiddleware()
      )
    ),
  );
};
```
Also, I have this bit about gatsby-plugin-react-redux in my gatsby-config.js:
```
  {
      resolve: `gatsby-plugin-react-redux`,
      options: {
        // [required] - path to your createStore module
        pathToCreateStoreModule: './src/state/createStore',
        // [optional] - options passed to `serialize-javascript`
        // info: https://github.com/yahoo/serialize-javascript#options
        // will be merged with these defaults:
        serialize: {
          space: 0,
          isJSON: true,
          unsafe: false,
        },
        // [optional] - if true will clean up after itself on the client, default:
        cleanupOnClient: true,
        // [optional] - name of key on `window` where serialized state will be stored, default:
        windowKey: '__PRELOADED_STATE__',
      },
    },
```
I see that gatsby provides this "preloadedState" object, but I am unsure how to save things into it and if it is indeed meant to be synced with localstorage. Appreciate the help. Also, I am planning to publish list to the list of official gatsby starters to any feedback and other constructive criticism would be great.
Thanks!

**Comment by le0nik** [comment]
Hi, `preloadedState` which this plugin passes into your `createStore` function is the state that was serialized on the server during build time.

You could probably merge states from the server and localStorage like this:

```js
// preloadedState will be passed in by the gatsby plugin
export default preloadedState => {
  return createStore(
    combinedReducers,
    {
      ...preloadedState,
      ...load({ states: ['loginCustomMiddleware'], disableWarnings: true }),
    },
    composeWithDevTools(
      applyMiddleware(
        save({ states: ['loginCustomMiddleware'] }),
        todosCustomMiddleware(),
        loginCustomMiddleware()
      )
    ),
  );
};
```

Or you can use something like https://lodash.com/docs/4.17.15#merge if you want to perform a deep merge.

**Comment by JimLynchCodes** [comment]
Thanks @le0nik!

It is a brilliant idea to spread both things into one object, and yes it worked for me!!

_Note: Also, in my redux store the data was being saved to a different field name so I needed to also change "loginCustomMiddleware" to "loginReducer".

Thanks!
👍

**Comment by JimLynchCodes** [comment]
@le0nik thanks, it's working for me when I run `gatsby develop`, but when I try to build it gives me an error that localstorage is not available when server side rendering... do you have any advice for working around this?

Thanks!

**Comment by le0nik** [comment]
You can either polyfill localStorage on the server or add a check like `typeof window !== 'undefined'` before calling `load`.

At this point I'm going to close this issue because it's not related to this gatsby plugin.
You can create an issue in the repo of the localStorage redux utility that you're using or on stackoverflow.

**Comment by JimLynchCodes** [comment]
ok thanks 👍

**Comment by ghost** [comment]
Hi please include a simple guide to save redux states in localStorage and then load them when the page refresh has happened in other words how to persist redux state in the browser so when the user refreshes the page the states are there and has not been reseted to the initial state . Thanks
